### ISSUE TITLE
Serverless Deploy

### ISSUE THREAD

**Issue by jclaveau** [jclaveau/strapi-experiments#118]
### Goals
- Simple deploy
- Cheap solution / Estimate costs
- Simple development

### Acceptance criteria
- Deploy on AWS
- Images must not be deleted when the Lambda is stopped
- Smoke tests?
- monorepo

### Todo
- [ ] Deploy on AWS
    - https://blog.vikfand.com/posts/serverless-strapi-4-guide/   
    - [x] Setup serverless
    - [x] Configure AWS
        - [x] Multi-account AWS https://spin.atomicobject.com/2020/11/03/multiple-aws-credentials-config/
                https://direnv.net/
        - [x] Add PGSQl instance https://eu-west-3.console.aws.amazon.com/rds/home?region=eu-west-3#dbinstance:id=strapi-4-serverless-demo-dev-postgresqlrdsinstance-fj2rckgjkyfe
        - [ ] Add route from subnet to apigateway
            - https://eu-west-3.console.aws.amazon.com/vpc/home?region=eu-west-3#RouteTableDetails:RouteTableId=rtb-04157dcec73fb1bb2
            - https://eu-west-3.console.aws.amazon.com/vpc/home?region=eu-west-3#VpcDetails:VpcId=vpc-009a27f9e39ea3e2e
            - https://eu-west-3.console.aws.amazon.com/vpc/home?region=eu-west-3#EditRoutes:RouteTableId=rtb-04157dcec73fb1bb2
        + [ ] Inbound rule for Security Group https://eu-west-3.console.aws.amazon.com/ec2/v2/home?region=eu-west-3#ModifyInboundSecurityGroupRules:securityGroupId=sg-0ca378da8c707c1fc
    + [ ] Deploy
    + [ ] Github Workflow
+ [ ] CDN for assets
+ [ ] Smoke tests

### Resources
- https://github.com/serverless/serverless
- https://blog.vikfand.com/posts/serverless-strapi-4-guide/
- https://github.com/serverless/examples
- https://www.serverless.com/blog/structuring-a-real-world-serverless-app
- https://github.com/serverless/serverless/issues/9095

### Next 
- Terraform? https://github.com/yasudacloud/terraform_strapi_serverless/blob/main/serverless/package.json
- Static site on Netlify or Vercel?
- Monorepo with NX? https://github.com/ngneat/nx-serverless/blob/main/services/todos/serverless.ts
- Nest Apps https://github.com/jclaveau/strapi-experiments/issues/123
- Scheduled Warmup https://github.com/juanjoDiaz/serverless-plugin-warmup
