### ISSUE TITLE
Docker compose && Heroku

### ISSUE THREAD

**Issue by jclaveau** [jclaveau/strapi-experiments#18]
### Goals
- [ ] Easy dev bootstrap (deps)
- [ ] Smooth dev workflow
- [ ] Creation of app on heroku
- [ ] Github workflow for 

### Todo
- [ ] dockercompse.dev.yml
  - [ ] Use PostgreSQL 
- [ ] heroku.yml

### Resources
-
